version: "2.1"
services:
  dashboard:
    image: "registry.infomaker.io/dashboard-devbox:latest"
    ports:
      - "5002:5002"
    depends_on:
      dynamodb:
        condition: service_started
    environment:
      - DB_PORT=5002
      - API_URL=http://localhost:8080
      - ENV=local
      - REAL_ENV=local

      # AWS config
      - AWS_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_S3_ENDPOINT=minio:9000
      - AWS_DDB_ENDPOINT=dynamodb:8000

      # Workspace's configs s3 bucket credentials
      - WORKSPACES_ICONS_BUCKET_NAME=workspaces-icons-local
      - WORKSPACES_ICONS_BUCKET_ACCESS_KEY_ID=dblocals3
      - WORKSPACES_ICONS_SECRET_ACCESS_KEY=dblocals3

      # Plugin's configs s3 bucket credentials
      - PLUGINS_CONFIG_BUCKET_NAME=plugin-config-local
      - PLUGINS_CONFIG_BUCKET_ACCESS_KEY_ID=dblocals3
      - PLUGINS_CONFIG_SECRET_ACCESS_KEY=dblocals3

      # Plugins s3 bucket credentials
      - PLUGINS_BUCKET_NAME=plugins-dev
      - PLUGINS_BUCKET_ACCESS_KEY_ID=xxx
      - PLUGINS_BUCKET_SECRET_ACCESS_KEY=xxx

      # DynamoDB Dashboard's tables names
      - WORKSPACE_TABLE_NAME=dashboard-workspace
      - STORAGE_TABLE_NAME=dashboard-storage
      - PLUGIN_TABLE_NAME=dashboard-plugin
      - PROFILE_TABLE_NAME=dashboard-profile

      - AVAILABLE_PLUGINS_URL=https://s3-eu-west-1.amazonaws.com/plugins-dev/available.json

      # Vars for IM.ID
      - TRUST_PROXY=true
      - MASTER_SECRET=oh-so-secret
      - SERVICE_TOKEN_SIGN_SECRET=puzzles
      - IM_LOG_NAME=dashboard
      - IM_LOG_LEVEL=error
  dynamodb:
    image: "instructure/dynamo-local-admin"
    ports:
      - "8000:8000"
  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    volumes:
      - ./s3:/export
    environment:
      - "MINIO_ACCESS_KEY=dblocals3" # should be used for CONFIG_BUCKET_ACCESS_KEY_ID locally
      - "MINIO_SECRET_KEY=dblocals3" # should be used for CONFIG_SECRET_ACCESS_KEY locally
    command: server /export
  mock-imsg:
    image: infomakerscandinaviaab/imid_mock-imsg:0.0.2
    healthcheck:
        test: "curl --fail http://localhost:8080/imsg-service/v1/health || exit 1"
        interval: 2s
        timeout: 1s
        retries: 20
    ports:
        - 8080:8080
    environment:
        PORT: 8080
        INTERNAL_SERVICE_URL: http://dashboard:5002
        SERVICE_TOKEN_SIGN_SECRET: puzzles
        SERVICE_TOKEN_PAYLOAD: |-
            {
                "org": "infomaker",
                "sub": "infomaker_6c0ed3cf-1032-4c29-ba75-85e547722295",
                "groups": [],
                "permissions": [
                    "dashboard:dashboard/load",
                    "dashboard:plugin/getAvailable",
                    "dashboard:plugin/getByBundle",
                    "dashboard:plugin/install",
                    "dashboard:plugin/update",
                    "dashboard:profile/create",
                    "dashboard:profile/delete",
                    "dashboard:proxy/exectue",
                    "dashboard:storage/delete",
                    "dashboard:storage/get",
                    "dashboard:storage/save",
                    "dashboard:user/me",
                    "dashboard:workspace/create",
                    "dashboard:workspace/delete",
                    "dashboard:workspace/encryption",
                    "dashboard:workspace/history",
                    "dashboard:workspace/update",
                    "dashboard:workspace/uploadIcon"
                ],
                "userinfo": {
                    "given_name": "Pelle",
                    "family_name": "Plutt",
                    "email": "pelle.plutt@infomaker.io"
                }
            }
        IM_LOG_NAME: mock-imsg
        IM_LOG_LEVEL: debug
      