version: "2.1"

services:
  dashboard:
    image: "infomakerscandinaviaab/dashboard-devbox:2.0.0-devbox"
    ports:
      - "5002:5002"
    depends_on:
      dynamodb:
        condition: service_started
    environment:
      - DB_PORT=5002
      - API_PORT=8080
      - BASE_URL=localhost
      - MASTER_SECRET=oh-so-secret
      - SERVICE_TOKEN_SIGN_SECRET=puzzles
      - PROXY_WHITELIST_DOMAINS=infomaker.io,navigacloud.com

  dynamodb:
    image: "instructure/dynamo-local-admin"
    ports:
      - "8000:8000"

  minio:
    image: "minio/minio"
    ports:
      - "9000:9000"
    volumes:
      - ./s3:/export
    environment:
      - "MINIO_ACCESS_KEY=dblocals3"
      - "MINIO_SECRET_KEY=dblocals3"
    command: server /export
    
  mock-imsg:
    image: infomakerscandinaviaab/imid_mock-imsg:0.4.3
    healthcheck:
      test: "curl --fail http://localhost:8080/imsg-service/v1/health || exit 1"
      interval: 2s
      timeout: 1s
      retries: 20
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      IM_LOG_LEVEL: debug
      IM_LOG_NAME: mock-imsg
      SERVICE_TOKEN_SIGN_SECRET: puzzles
      INCLUDE_IMID_TOKEN_IN_REQUEST: 'true'
      INTERNAL_SERVICE_URL: http://dashboard:5002
      SERVICE_TOKEN_PAYLOAD: |-
        {
            "org": "infomaker",
            "sub": "infomaker_6c0ed3cf-1032-4c29-ba75-85e547722295",
            "groups": [],
            "permissions": {
              "org": ["dashboard:user/me"],
              "units": {
                "dashboard": [
                  "dashboard:group/admin",
                  "dashboard:group/powerUser",
                  "dashboard:group/user",
                  "dashboard:group/readOnly",
                  "dashboard:dashboard/load",
                  "dashboard:plugin/getAvailable",
                  "dashboard:plugin/getByBundle",
                  "dashboard:plugin/install",
                  "dashboard:plugin/update",
                  "dashboard:plugin/delete",
                  "dashboard:profile/create",
                  "dashboard:profile/delete",
                  "dashboard:proxy/exectue",
                  "dashboard:storage/delete",
                  "dashboard:storage/get",
                  "dashboard:storage/save",
                  "dashboard:user/me",
                  "dashboard:config-key/create",
                  "dashboard:config-key/delete",
                  "dashboard:config-key/update",
                  "dashboard:workspace/create",
                  "dashboard:workspace/delete",
                  "dashboard:workspace/encryption",
                  "dashboard:workspace/history",
                  "dashboard:workspace/update",
                  "dashboard:workspace/uploadIcon",
                  "dashboard:workspace/updateProfiles"
                ]
              }
            },
            "userinfo": {
                "given_name": "Dashboard",
                "family_name": "User",
                "email": "dashboard-user@infomaker.io"
            }
        }
